# Generated by Django 3.2.3 on 2021-05-20 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('avata', models.ImageField(upload_to='Anh_Tuong')),
            ],
        ),
        migrations.CreateModel(
            name='AbilityGeneral',
            fields=[
                ('general', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.general')),
                ('name_passive', models.CharField(max_length=100)),
                ('content_passive', models.CharField(max_length=200)),
                ('image_passive', models.ImageField(upload_to='ability')),
                ('name_q', models.CharField(max_length=100)),
                ('content_q', models.CharField(max_length=200)),
                ('image_q', models.ImageField(upload_to='ability')),
                ('name_w', models.CharField(max_length=100)),
                ('content_w', models.CharField(max_length=200)),
                ('image_w', models.ImageField(upload_to='ability')),
                ('name_e', models.CharField(max_length=100)),
                ('content_e', models.CharField(max_length=200)),
                ('image_e', models.ImageField(upload_to='ability')),
                ('name_r', models.CharField(max_length=100)),
                ('content_r', models.CharField(max_length=200)),
                ('image_r', models.ImageField(upload_to='ability')),
                ('video_ability', models.FileField(upload_to='video')),
            ],
        ),
        migrations.CreateModel(
            name='IntroduceGeneral',
            fields=[
                ('general', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.general')),
                ('image', models.ImageField(upload_to='Anh_Tuong')),
                ('role', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=0)),
                ('diffculty', models.CharField(max_length=50)),
                ('introduction', models.TextField(max_length=300)),
                ('video_intro_id', models.FileField(upload_to='video')),
            ],
        ),
        migrations.CreateModel(
            name='SkinGeneral',
            fields=[
                ('general', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.general')),
                ('name_1', models.CharField(max_length=100)),
                ('image_1', models.ImageField(upload_to='skin')),
                ('name_2', models.CharField(max_length=100)),
                ('image_2', models.ImageField(upload_to='skin')),
                ('name_3', models.CharField(max_length=100)),
                ('image_3', models.ImageField(upload_to='skin')),
                ('name_4', models.CharField(max_length=100)),
                ('image_4', models.ImageField(upload_to='skin')),
                ('name_5', models.CharField(max_length=100)),
                ('image_5', models.ImageField(upload_to='skin')),
            ],
        ),
    ]
